inputs:
    setDev: true
    setLanguages: 
    - php
    setFrameworks: 
    # - suitecrm
    # - codeigniter
    # - wordpress
    - prestashop
    - symfony
    setSources: ~
    setSinks: ~
    setValidators: ~
    setSanitizers: ~
    setCustomRules: ~
    setIncludes: ~
    setExcludes: 
        exclude_files:
        # - "/srv/www/htdocs/phpMyAdmin/libraries/tcpdf/fonts/dejavusans.php"
        - "*.tar.gz"
        - "*.zip"
        - "*.jpeg"
        - "*.jpg"
        - "*.png"
        - "*.gif"
        exclude_folders: 
        - ".git"
        - "images"
        - "/opt/mount/var/cache"
        - "/opt/mount/images"
        - "/opt/mount/.git"
        - "/opt/mount/vendor"
        - "/opt/mount/localization"
    setFolder: "/opt/mount/"
    setFile: ~
    setCode: ~
    setResolvedIncludes: ~
    setFalsePositives: ~
    
outputs:
    taintedFlow: false
    resolveIncludes: false
    resolveIncludesFile: ~
    
options:
    setAnalyzeIncludes: true
    setAnalyzeFunctions: true
    setAnalyzeHardRules: true
    setPrintFile: true
    setPrintWarning: false
    setPrettyPrint: true
    setLimitTime: 10
    setLimitDefs: 3000
    setLimitSize: 500000
